#
# eChronos Real-Time Operating System
# Copyright (C) 2015  National ICT Australia Limited (NICTA), ABN 62 102 206 173.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, version 3, provided that these additional
# terms apply under section 7:
#
#   No right, title or interest in or to any trade mark, service mark, logo or
#   trade name of of National ICT Australia Limited, ABN 62 102 206 173
#   ("NICTA") or its licensors is granted. Modified versions of the Program
#   must be plainly marked as such, and must not be distributed using
#   "eChronos" as a trade mark or product name, or misrepresented as being the
#   original Program.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# @TAG(NICTA_AGPL)
#

version: 1.0.{build}
branches:
    except:
        - archive/*
        - abandoned/*
clone_depth: 1
environment:
    PATH: C:\msys64\mingw64\bin;%PATH%;C:\Program Files\Git\cmd
    matrix:
        - PYTHON: "C:\\Python36-x64\\python"
        - PYTHON: "C:\\Python35-x64\\python"
        # Python 3.4 and 3.4 are no longer officially supported.
        # Therefore, the project also does not have to support them.
        # However, we still test against those versions to learn when we break support for them.
        - PYTHON: "C:\\Python34-x64\\python"
        - PYTHON: "C:\\Python33-x64\\python"
build_script: test_setup.bat
test_script: test.bat
artifacts:
- path: packages\*\rtos-*\docs.pdf
  name: documentation
deploy: off
